# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: linode
#   namespace: demo
# stringData:
#   AWS_ACCESS_KEY_ID: <>
#   AWS_SECRET_ACCESS_KEY: <>
#   AWS_ENDPOINT: https://us-east-1.linodeobjects.com

# ---
apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: linode
  namespace: demo
spec:
  storage:
    provider: s3
    s3:
      endpoint: https://us-east-1.linodeobjects.com
      bucket: mg4
      region: us-east-1
      prefix: test
      secret: linode
  usagePolicy:
    allowedNamespaces:
      from: All
  default: true 
  deletionPolicy: WipeOut