apiVersion: archiver.kubedb.com/v1alpha1
kind: MongoDBArchiver
metadata:
  name: mongodbarchiver-sample
  namespace: demo
spec:
  pause: false
  databases:
    namespaces:
      from: "Same"
    selector:
      matchLabels:
        archiver: "true"
  retentionPolicy:
    name: mongodb-retention-policy
    namespace: demo
  encryptionSecret:
    name: encrypt-secret
    namespace: demo
  fullBackup:
    driver: VolumeSnapshotter
    task:
      params:
        volumeSnapshotClassName: longhorn-vsc  
    scheduler: # configuration for backup triggering cronJob. (~ bc.spec.sessions[].scheduler)
      successfulJobsHistoryLimit: 2
      failedJobsHistoryLimit: 2
      schedule: "*/5 * * * *"
      jobTemplate:
        backoffLimit: 3
        template:
          spec:
            # serviceAccountName: my-cron-sa # the sa of trigger job
            securityContext:
              runAsUser: 999
      concurrencyPolicy: Allow
    containerRuntimeSettings: # configuration for backup executor container. (~ bc.spec.sessions[].addon.containerRuntimeSettings)
      resources:
        requests:
          memory: 300Mi
    jobTemplate: # configuration for backup job. (~ bc.spec.sessions[].addon.jobTemplate)
      spec:
          # serviceAccountName: my-backup-sa # the sa of backup job
          securityContext:
            runAsUser: 999
    retryConfig:
      maxRetry: 2
      delay: 30s
    timeout: 30m
    sessionHistoryLimit: 3
  walBackup: # configuration for sidekick
    runtimeSettings:
      pod: #(~sidekick.spec)
        serviceAccountName: my-wal-sa
      container: #(~sidekick.spec.containers[wal-g container])
        resources:
          requests:
            memory: 300Mi
    # configSecret:
    #   name:
    #   envToSecretKey:
  manifestBackup: # all the options(except driver) from fullBackup are also available here.
    scheduler:
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
      schedule: "*/3 * * * *"
    sessionHistoryLimit: 2
  backupStorage:
    ref:
      name: s3-storage
      namespace: demo
    subDir: /sub
  deletionPolicy: WipeOut