apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-rs
  namespace: demo
  labels:
    archiver: "true"
spec:
  version: "6.0.12"
  replicaSet:
    name: "rs" 
  replicas: 3
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
  storage:
    # storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi