apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mg-rs-restored
  namespace: demo
spec:
  version: "5.0.23"
  replicaSet:
    name: "rs" 
  replicas: 3
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
  storage:
    # storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  init:
    archiver:
      recoveryTimestamp: "2024-10-08T13:52:00Z"
      encryptionSecret:
        name: encrypt-secret
        namespace: demo
      fullDBRepository:
        name: repl6-full
        namespace: demo
      manifestRepository:
        name: repl6-manifest
        namespace: demo
  terminationPolicy: WipeOut

   # restore.go:392] 2023-11-28 15:50:02 +0000 UTC 2023-11-28 21:35:01 +0000 UTC ;;; 2023-11-28T15:50:02Z 2023-11-28T21:35:01Z