apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: linode-secret
  namespace: demo
stringData:
  AWS_ACCESS_KEY_ID: <>
  AWS_SECRET_ACCESS_KEY: <>
  AWS_ENDPOINT: https://us-east-1.linodeobjects.com


kubectl create secret generic -n demo gcs-secret \
  --from-literal=GOOGLE_PROJECT_ID=appscode-testing \
  --from-file=./GOOGLE_SERVICE_ACCOUNT_JSON_KEY \
#   --from-literal=RESTIC_PASSWORD=12345