apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: mg4
  namespace: demo
spec:
  version: "4.4.26"
  replicaSet:
    name: "rs0"
  replicas: 3
  storageType: Durable
  podTemplate:
    spec:
      containers:
      - name: mongodb
        resources:
          requests:
            cpu: 600m
            memory: 600Mi
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut