apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: sample3
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: MongoDB
    namespace: demo
    name: specific-mg5
  # manifestOptions:
  #   restoreNamespace: demo2
  #   mongoDB:
  #     db: true
  #     dbName: new-mongodb
  #     authSecret: true
  #     configSecret: true
  dataSource:
    snapshot: specific-repo-db-backup-specific-db-1709622361
    repository: specific-repo
    encryptionSecret:
      name: encrypt-secret # some addon may not support encryption
      namespace: demo
  addon:
    name: mongodb-addon
    tasks:
    - name: logical-backup-restore
      params:
        args: --db=testdb