apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.kubestash.com/v1alpha1","kind":"BackupStorage","metadata":{"annotations":{},"name":"linode","namespace":"demo"},"spec":{"default":true,"deletionPolicy":"WipeOut","storage":{"provider":"s3","s3":{"bucket":"mg4","endpoint":"https://us-east-1.linodeobjects.com","prefix":"test","region":"us-east-1","secret":"linode"}},"usagePolicy":{"allowedNamespaces":{"from":"All"}}}}
  creationTimestamp: "2023-08-22T08:13:22Z"
  finalizers:
  - kubestash.com/cleanup
  generation: 1
  name: linode
  namespace: demo
  resourceVersion: "396424"
  uid: 6e922e43-f955-4701-8fe2-0dd7e3890ea7
spec:
  default: true
  deletionPolicy: WipeOut
  storage:
    provider: s3
    s3:
      bucket: mg4
      endpoint: https://us-east-1.linodeobjects.com
      prefix: test
      region: us-east-1
      secret: linode
  usagePolicy:
    allowedNamespaces:
      from: All
status:
  conditions:
  - lastTransitionTime: "2023-08-22T08:13:24Z"
    message: Successfully initialized backend.
    reason: BackendInitializationSucceeded
    status: "True"
    type: BackendInitialized
  - lastTransitionTime: "2023-08-22T08:13:24Z"
    message: Baackend secret exists.
    reason: BackendSecretAvailable
    status: "True"
    type: BackendSecretFound
  phase: Ready
  repositories:
  - name: linode-repo
    namespace: demo
    path: /full
    synced: true
