apiVersion: storage.kubestash.com/v1alpha1
kind: Repository
metadata:
  creationTimestamp: "2023-08-22T08:15:04Z"
  finalizers:
  - kubestash.com/cleanup
  generation: 1
  name: linode-repo
  namespace: demo
  resourceVersion: "397313"
  uid: 75a70af8-461d-4dc0-8381-554d28b49bf3
spec:
  appRef:
    apiGroup: kubedb.com
    kind: MongoDB
    name: standalone
    namespace: demo
  deletionPolicy: Delete
  encryptionSecret:
    name: encrypt-secret
    namespace: demo
  path: /full
  storageRef:
    apiGroup: storage.kubestash.com
    kind: BackupStorage
    name: linode
    namespace: demo
status:
  conditions:
  - lastTransitionTime: "2023-08-22T08:15:06Z"
    message: Successfully initialized repository
    reason: RepositoryInitializationSucceeded
    status: "True"
    type: RepositoryInitialized
  phase: Ready
  recentSnapshots:
  - name: linode-repo-db-backup-frequent-backup-1692692160
    phase: Succeeded
    session: frequent-backup
    size: 1.630 KiB
    snapshotTime: "2023-08-22T08:16:27Z"
  - name: linode-repo-db-backup-frequent-backup-1692692520
    phase: Succeeded
    session: frequent-backup
    size: 3.265 KiB
    snapshotTime: "2023-08-22T08:22:26Z"
