apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: db-backup
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: Postgres
    namespace: demo
    name: pgc
  backends:
  - name: linode-backend
    storageRef:
      namespace: demo
      name: s3-storage
    retentionPolicy:
      name: pg-retention-policy
      namespace: demo
  sessions:
  # - name: specific-db
  #   sessionHistoryLimit: 3
  #   scheduler:
  #     schedule: "*/3 * * * *"
  #     successfulJobsHistoryLimit: 2
  #     failedJobsHistoryLimit: 2
  #     jobTemplate:
  #       backoffLimit: 1
  #   repositories:
  #   - name: specific-repo
  #     backend: linode-backend
  #     directory: /specific
  #     encryptionSecret:
  #       name: encrypt-secret # some addon may not support encryption
  #       namespace: demo
  #   addon:
  #     name: mongodb-addon
  #     tasks:
  #     - name: logical-backup
  #       params:
  #         args: --db=testdb
  - name: full-db
    sessionHistoryLimit: 3
    scheduler:
      schedule: "*/5 * * * *"
      successfulJobsHistoryLimit: 2
      failedJobsHistoryLimit: 2
      jobTemplate:
        backoffLimit: 1
    repositories:
    - name: full-repo
      backend: linode-backend
      directory: /full
      encryptionSecret:
        name: encrypt-secret # some addon may not support encryption
        namespace: demo
    addon:
      name: postgres-addon
      tasks:
      - name: logical-backup
      jobTemplate:
        spec:
          securityContext:
            runAsUser: 1000660000