apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: sample
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: Postgres
    namespace: demo
    name: pgrestore
  # manifestOptions:
  #   restoreNamespace: demo2
  #   mongoDB:
  #     db: true
  #     dbName: new-mongodb
  #     authSecret: true
  #     configSecret: true
  dataSource:
    snapshot: full-repo-db-backup-full-db-1709622300
    repository: full-repo
    encryptionSecret:
      name: encrypt-secret # some addon may not support encryption
      namespace: demo
  addon:
    name: postgres-addon
    tasks:
      - name: logical-backup-restore
    jobTemplate:
      spec:
        securityContext:
          runAsUser: 1000660000


# CREATE TABLE hi(id int);
# INSERT INTO hi (id) values(generate_series(1,500));
# SELECT count(*) from hi;
