apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: s3-storage
  namespace: demo
spec:
  storage:
    provider: s3
    s3:
      endpoint: http://minio.minio.svc:9000
      bucket: arnob
      region: us-east-1
      prefix: /harvester-minio
      secretName: minio-secret
  usagePolicy:
    allowedNamespaces:
      from: All
  deletionPolicy: WipeOut