apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: mg-backup
  namespace: demo
spec:
  schedule: "*/2 * * * *"
  # task:
  #   name: mongodb-backup-4.4.6
  repository:
    name: lke
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mg-rs
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true