apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: lke
  namespace: demo
spec:
  backend:
    s3:
      endpoint: us-east-1.linodeobjects.com
      bucket: arnob
      prefix: shard #rs #standalone
      region: us-east-1
    storageSecretName: lke-creds