apiVersion: stash.appscode.com/v1beta1
kind: RestoreSession
metadata:
  name: mg-restore
  namespace: demo
spec:
  # task:
  #   name: mongodb-restore-4.2.3
    # params:
    # - name: "args"
    #   value: "--preserveUUID true --drop"
  repository:
    name: lke
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mg4-res
  rules:
  - snapshots: [latest]
